# **Tensor Flow**

In [6]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.5.0'

In [4]:
b = tf.constant(10, dtype = tf.int64)
b.numpy()

10

In [5]:
# Definign 2 D array or matrix
c = tf.constant([[4,2], 
                [9,2]]
                )
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 2]])>

In [8]:
c.numpy()

array([[4, 2],
       [9, 2]])

In [9]:
print(f"Shape: {c.shape}")
print(f"Type: {c.dtype}")

Shape: (2, 2)
Type: <dtype: 'int32'>


In [15]:
print(np.zeros((3,3))) # Numpy way
print(tf.zeros(shape = (2,3))) # Tensorflow way
print(np.ones((3,3))) # Numpy way
print(tf.ones(shape = (2,3))) # Tensorflow way

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [24]:
var1 = tf.constant([
                    [1,2,3],
                    [ 3,4,5]
                    ])
print(var1.numpy())   
var2 = tf.constant([
                    [3,4,5],
                    [ 1,2,3]
                    ])
print(var2.numpy())    

result = tf.add(var1, var2)

print(result.numpy())             

[[1 2 3]
 [3 4 5]]
[[3 4 5]
 [1 2 3]]
[[4 6 8]
 [4 6 8]]


In [32]:
print(tf.random.normal(shape = (2,2), mean=0)) # Craeting 2X2 marix with mean equal to 0

var0 = tf.Variable(42) # rank zero tensor output
print(var0.numpy()) 

var1 = tf.Variable([[
                    [0,1,2],
                    [3,4,5],
                    [9,10,11]
                    ]]) # rank 3 tensor output
print(var1.numpy()) 


tf.Tensor(
[[-2.1782393  -0.32456023]
 [ 2.2323263   0.79020345]], shape=(2, 2), dtype=float32)
42
[[[ 0  1  2]
  [ 3  4  5]
  [ 9 10 11]]]


In [36]:
var4 = tf.Variable(45, dtype = tf.float64) # Defining float point variable
print(var4.dtype)
print(var4.numpy())

<dtype: 'float64'>
45.0


In [39]:
var5 = tf.constant([1,2,3,4,5])
rank = var5.ndim # Getting rank
print(rank)

1


**Implementation on simple dataset**

In [44]:
data = tf.keras.datasets.mnist
(train_x, train_y), (test_x, test_y) = data.load_data()

In [45]:
data

<module 'tensorflow.keras.datasets.mnist' from 'd:\\Personal Files\\NLP_Bootcamp\\venv\\lib\\site-packages\\tensorflow\\keras\\datasets\\mnist\\__init__.py'>

In [46]:
epochs = 10
batch_size = 32

In [47]:
train_x, test_x = tf.cast(train_x/255, tf.float64), tf.cast(test_x/255, tf.float64) # Normalizing
train_y, test_y = tf.cast(train_y/255, tf.int64), tf.cast(test_y/255, tf.int64) # Normalizing

In [48]:
train_y

<tf.Tensor: shape=(60000,), dtype=int64, numpy=array([0, 0, 0, ..., 0, 0, 0], dtype=int64)>

In [50]:
model = tf.keras.models.Sequential([
tf.keras.layers.Flatten(input_shape = (28,28)), # Flatten will conver 2-D or 3-D into 1-D for the input
tf.keras.layers.Dense(512, activation = tf.nn.relu), # Fully connected layer, 512 neuron, 512 data at a point will be passed
tf.keras.layers.Dropout(0.2), # Regularization technique -  we can prevent overfitting. using droput we can pass random % (here is 20%) of data. Everytime we are updating 20 % of the data here
tf.keras.layers.Dense(10, activation = tf.nn.softmax) # Output layer, Softmax for multiclassification problem
])

In [51]:
optimizer = tf.keras.optimizers.Adam()

In [52]:
model.compile(optimizer, loss = "SparseCategoricalCrossentropy", metrics = ['accuracy'])

In [53]:
model.fit(train_x, train_y, batch_size = 32, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 12s 5ms/step - loss: 0.0026 - accuracy: 0.9995
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 6.3772e-07 - accuracy: 1.0000
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 1.7801e-07 - accuracy: 1.0000
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 9.6741e-08 - accuracy: 1.0000
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 4.4863e-08 - accuracy: 1.0000


In [54]:
model.evaluate(test_x, test_y)

313/313 [==============================] - 1s 3ms/step - loss: 1.0967e-09 - accuracy: 1.0000


[1.0967239338910417e-09, 1.0]

In [55]:
model.save("./model.h5")

**2nd way to create model**

In [57]:
model1 = tf.keras.models.Sequential()
model1.add(tf.keras.layers.Flatten(input_shape = (28,28))) # Flatten will conver 2-D or 3-D into 1-D for the input
model1.add(tf.keras.layers.Dense(512, activation = tf.nn.relu)) # Fully connected layer, 512 neuron, 512 data at a point will be passed
model1.add(tf.keras.layers.Dropout(0.2)) # Regularization technique -  we can prevent overfitting. using droput we can pass random % (here is 20%) of data. Everytime we are updating 20 % of the data here
model1.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax)) # Output layer, Softmax for multiclassification problem
optimizer = tf.keras.optimizers.Adam()
model1.compile(optimizer, loss = "SparseCategoricalCrossentropy", metrics = ['accuracy'])
model1.fit(train_x, train_y, batch_size = 32, epochs = 5)


Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0026 - accuracy: 0.9995
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 1.2263e-06 - accuracy: 1.0000
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 3.8089e-07 - accuracy: 1.0000
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 1.8484e-07 - accuracy: 1.0000
Epoch 5/5
1875/1875 [==============================] - 10s 6ms/step - loss: 8.0269e-08 - accuracy: 1.0000


In [58]:
model1.evaluate(test_x, test_y)
model1.save("./model.h5")

313/313 [==============================] - 1s 3ms/step - loss: 1.9908e-09 - accuracy: 1.0000


**3rd Way to create model**

In [62]:
# model2 = tf.keras.models.Sequential()
# x= tf.keras.layers.Flatten(input_shape = (28,28))(model2) # Flatten will conver 2-D or 3-D into 1-D for the input
# y = tf.keras.layers.Dense(512, activation = tf.nn.relu)(x) # Fully connected layer, 512 neuron, 512 data at a point will be passed
# z = tf.keras.layers.Dropout(0.2)(y) # Regularization technique -  we can prevent overfitting. using droput we can pass random % (here is 20%) of data. Everytime we are updating 20 % of the data here
# a = tf.keras.layers.Dense(10, activation = tf.nn.softmax)(z) # Output layer, Softmax for multiclassification problem
# optimizer = tf.keras.optimizers.Adam()
# a.compile(optimizer, loss = "SparseCategoricalCrossentropy", metrics = ['accuracy'])
# a.fit(train_x, train_y, batch_size = 32, epochs = 5)
